### ISSUE TITLE
Como es el formato del DNI?

### ISSUE THREAD

**Issue by julianpoma** [64robots/nova-dni-field#1]
Hola! No encontre fotos de como es el formato del DNI. 

En Argentina también usamos DNI, con el siguiente formato: `##.###.###`. Por ejemplo: `40.123.456`

Me gustaria integrarlo a mi proyecto ! Un abrazo!

**Comment by beliolfa** [comment]
Hola! Iré actualizando la documentación cuando tenga un poco de tiempo.

El formato de DNI español es igual que el que comentas pero tiene una letra de control al final que es calculada con los dígitos. 12.345.678Z

La formula para calcular la letra del DNI y obtener el NIF es la siguiente: Tomamos el número completo de hasta 8 cifras de nuestro DNI, lo dividimos entre 23 y nos quedamos con el resto de dicha división. Ese resto corresponde con una letra del alfabeto.

Si esto coincide en argentina estaré encantado de indicarlo en la documentación.

Gracias!

**Comment by julianpoma** [comment]
Hola! No, lamentablemente en Argentina no usamos la letra del alfabeto. Solamente los 8 dígitos.
No te preocupes y gracias por la rápida respuesta!
