### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by Hoddix** [64robots/nova-dni-field#3]
Hola, 
Cuando intentas comprobar este CIF: B92705417, lanza esta excepción "**A non-numeric value encountered**" debido a la comprobación de la línea 28 en el "**ValidateDni.php**".

Una parte de la validación es coger los números impares multiplicarlos por 2, sumar las cifras del resultado entre ellas, para después sumar todas. 
Posiciones impares:
9 * 2 = 18 -> 1 + 8 = 9
7 * 2 = 14 -> 1 + 4 = 5
5 * 2 = 10 -> 1 + 0 = 1
1 * 2 = 2 -> = 2

En este ejemplo el último número impar del CIF, es el número 1, que multiplicado por 2 da 2, lo cual, la línea 28 del código no puede sacar la segunda cifra para realizar la suma entre ellas:

<code>$suma += substr((2 * $num[$i]),0,1) + substr((2 * $num[$i]), 1, 1);</code>

y por eso lanza esta excepción "**A non-numeric value encountered**".

Esto se soluciona con la siguiente línea:

<code>$suma += array_sum(str_split(2 * $num[$i]));</code>

Separamos las cifras de la multiplicación de 2 * $num[$i], para después sumarlas entre ellas, por último, lo unimos con la suma principal.

**Comment by beliolfa** [comment]
Gracias por el fix!

Fixed in 1.0.2
